--ALTER DATABASE InVoiceXML SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

USE [master]
GO

DROP DATABASE IF EXISTS InVoiceXML;
GO

/****** Object:  Database [InVoiceXML]    Script Date: 6/9/2018 12:17:38 PM ******/
CREATE DATABASE [InVoiceXML]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InVoiceXML', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\InVoiceXML.mdf' , SIZE = 131072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InVoiceXML_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\InVoiceXML_log.ldf' , SIZE = 65536KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [InVoiceXML] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InVoiceXML].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InVoiceXML] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InVoiceXML] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InVoiceXML] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InVoiceXML] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InVoiceXML] SET ARITHABORT OFF 
GO

ALTER DATABASE [InVoiceXML] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InVoiceXML] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InVoiceXML] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InVoiceXML] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InVoiceXML] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InVoiceXML] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InVoiceXML] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InVoiceXML] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InVoiceXML] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InVoiceXML] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InVoiceXML] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InVoiceXML] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InVoiceXML] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InVoiceXML] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InVoiceXML] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InVoiceXML] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InVoiceXML] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InVoiceXML] SET RECOVERY FULL 
GO

ALTER DATABASE [InVoiceXML] SET  MULTI_USER 
GO

ALTER DATABASE [InVoiceXML] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InVoiceXML] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InVoiceXML] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InVoiceXML] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InVoiceXML] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InVoiceXML] SET QUERY_STORE = OFF
GO

USE [InVoiceXML]
GO

--ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [InVoiceXML] SET  READ_WRITE 
GO
